### ISSUE TITLE
Incorrect reflection for com.fasterxml.jackson.databind.ObjectMapper

### ISSUE THREAD

**Issue by FieryCod** [metosin/jsonista#51]
Native compilation with GraalVM NativeImage of application containing jsonista 0.3.2 provides error on runtime when no native-configurations are provided.

Stack trace:
```
Exception in thread "main" java.lang.IllegalArgumentException: No matching method registerModule found taking 1 args for class com.fasterxml.jackson.databind.ObjectMapper
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:127)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
        at jsonista.core$object_mapper.invokeStatic(core.clj:139)
        at jsonista.core$object_mapper.invoke(core.clj:102)
        at fierycod.holy_lambda.util$in__GT_edn_event.invokeStatic(util.cljc:27)
        at fierycod.holy_lambda.util$in__GT_edn_event.invoke(util.cljc:20)
        at fierycod.holy_lambda.util$http.invokeStatic(util.cljc:98)
        at fierycod.holy_lambda.util$http.doInvoke(util.cljc:81)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at fierycod.holy_lambda.native_runtime$fetch_aws_event.invokeStatic(native_runtime.clj:50)
        at fierycod.holy_lambda.native_runtime$fetch_aws_event.invoke(native_runtime.clj:48)
        at fierycod.holy_lambda.native_runtime$next_iter.invokeStatic(native_runtime.clj:78)
        at fierycod.holy_lambda.native_runtime$next_iter.invoke(native_runtime.clj:74)
        at clojure.lang.Var.invoke(Var.java:388)
        at example.core$_main.invokeStatic(core.cljc:23)
        at example.core$_main.invoke(core.cljc:23)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at example.core.main(Unknown Source)
``` 

GraalVM: 21.1.0
Version: jsonista 0.3.2

**Comment by ikitommi** [comment]
On JVM, there is no error on that. Pushed out `[metosin/jsonista "0.3.3"]` with explicit type hint on the module. Hopefully that helps.

**Comment by FieryCod** [comment]
@ikitommi I've reported not existing issue apparently.  Native configuration from jsonista "0.3.1" :/ was cached when tested native-image compile with "0.3.2". I'm really sorry for this mess. Feel free to close this issue at any time!

**Comment by ikitommi** [comment]
no prob :)
